version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    ports:
      - 5432:5432
    volumes:
      - data_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
     - static_value:/app/static/
     - media_value:/app/media/
    depends_on:
     - db
    env_file:
     - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
     - db

  nginx:
    image: nginx:1.21.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    env_file:
      - ./.env
    depends_on:
      - backend
      - frontend

volumes:
  data_value:
  static_value:
  media_value: