# Generated by Django 3.2.16 on 2023-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('authorized', 'authorized'), ('guest', 'guest')], default='guest', max_length=10, verbose_name='Роль'),
        ),
    ]
